Update cicd-cache.yml

diff --git a/cicd-cache.yml b/cicd-cache.yml
--- a/cicd-cache.yml
+++ b/cicd-cache.yml
@@ -1,18 +1,81 @@
-CONFIG_FILE="$(Build.SourcesDirectory)/eis-configurations/${BRANCH}_config.yml"
-OVERRIDE_FILE="$(Build.SourcesDirectory)/eis-configurations/${BRANCH}_override.yml"
+- stage: Release
+  displayName: Deploy Stage
+  pool:
+    name: TFS-RH-1
+  dependsOn:
+    - Validation_Stage
+    - Build
+  condition: |
+    and(
+      succeeded('Build'),
+      eq(dependencies.Validation_Stage.outputs['Validation_Job.val_task.DeployFlag'], 'true'),
+      ne(variables['Build.SourceBranchName'], 'main')
+    )
 
-if [ -f "$CONFIG_FILE" ]; then
-  COUNT=$(yq e "keys | map(select(. == \"$applicationName\")) | length" "$CONFIG_FILE")
-  if [ "$COUNT" -gt 1 ]; then
-    echo "ERROR: Config file '${BRANCH}_config.yml' has duplicate entries for key '$applicationName'."
-    exit 1
-  fi
-fi
+  jobs:
+    - deployment: DeployApp
+      displayName: Deployment Job
+      environment: $(Build.SourceBranchName)
+      workspace:
+        clean: all
 
-if [ -f "$OVERRIDE_FILE" ]; then
-  COUNT=$(yq e "keys | map(select(. == \"$applicationName\")) | length" "$OVERRIDE_FILE")
-  if [ "$COUNT" -gt 1 ]; then
-    echo "ERROR: Override file '${BRANCH}_override.yml' has duplicate entries for key '$applicationName'."
-    exit 1
-  fi
-fi
+      strategy:
+        runOnce:
+          deploy:
+            steps:
+
+              - download: current
+                artifact: drop
+
+              - task: CmdLine@2
+                displayName: Deploying Bar File
+                env:
+                  BRANCH: $(Build.SourceBranchName)
+                inputs:
+                  workingDirectory: $(Pipeline.Workspace)/drop
+                  script: |
+                    set -e
+                    . /opt/IBM/ace/server/bin/mqsiprofile
+
+                    IntegrationNode=($(yq e ".IntegrationNode" config.yml))
+                    ApplicationName=$(yq e ".ApplicationName" config.yml)
+                    IntegrationServer=($(yq e ".IntegrationServer" config.yml))
+
+                    broker_files=()
+
+                    for node in "${IntegrationNode[@]}"; do
+                      for broker_file in /home/devops/broker/$BRANCH/${node}*; do
+                        fname=$(basename "$broker_file")
+                        if [[ $fname =~ ^${node}_([0-9]+)\.broker$ ]]; then
+                          broker_files+=("$broker_file")
+                        fi
+                      done
+                    done
+
+                    if [ ${#broker_files[@]} -eq 0 ]; then
+                      echo "Error: No Integration Node found for $IntegrationNode"
+                      exit 1
+                    fi
+
+                    for broker_file in "${broker_files[@]}"; do
+                      servers=($(mqsilist -n "$broker_file" -w 5 | grep "running" | grep "Integration" | cut -d"'" -f2))
+
+                      if [ ${#servers[@]} -eq 0 ]; then
+                        echo "Error: Not able to access $broker_file or no Integration Server is running"
+                        exit 1
+                      fi
+
+                      for server in "${IntegrationServer[@]}"; do
+                        if printf '%s\n' "${servers[@]}" | grep -qx "$server"; then
+                          host=$(grep host "$broker_file" | awk -F'"' '{print $4}')
+                          echo "HOST: $host , IntegrationNode: $fname , IntegrationServer: $server"
+                          ibmint deploy \
+                            --input-bar-file "$ApplicationName.bar" \
+                            --integration-node-file "$broker_file" \
+                            --output-server "$server"
+                        else
+                            echo " Integration server $server name is incorrect or not running"
+                            exit 1  
+                        fi
+                      done
+                    done
