Update Logger

diff --git a/Logger b/Logger
--- a/Logger
+++ b/Logger
@@ -1,21 +1,19 @@
-variables:
-  ${{ if contains(variables['Build.SourceBranchName'], 'eapi') }}:
-    APP_NAME: EIS-API-LOGGER-eapi
-
-  ${{ elseif contains(variables['Build.SourceBranchName'], 'sapi') }}:
-    APP_NAME: EIS-API-LOGGER-sapi
-
+parameters:
+  - name: applicationName
+    type: string
+    default: ''
 
 stages:
 # ============== Validation and Initilization ============
 - stage: Validation_Stage
-  displayName: Validation
+  displayName: Validation and Intialization
   pool:
     name: TFS-RH-1
-      
-
   jobs:
     - job: Validation_Job
+      displayName: Validation
+      workspace:
+        clean: all
       steps:
 
         - checkout: self
@@ -28,106 +26,246 @@ stages:
           name: val_task
           env:
             BRANCH: $(Build.SourceBranchName)
-            APP_NAME: $(APP_NAME)
+          displayName: Validating repository
           inputs:
             script: |
               set -e
+              if [ -z "${{ parameters.applicationName }}" ]; then
+                applicationName=$(ls -1 $(Build.SourcesDirectory)/app | grep -vE "Config|README.md|azure-pipelines.yml" | tail -n 1)
+              else
+                applicationName="${{ parameters.applicationName }}"
+              fi
 
-              echo "App: $APP_NAME"
-              echo "Branch: $BRANCH"
+              echo "Application name : $applicationName"
+              echo "branch: $BRANCH"
+              echo "DONE 1"
 
-              CONFIG_FILE=$(Build.SourcesDirectory)/eis-configurations/"$BRANCH"_config.yml
+              if [ "$BRANCH" = "main" ]; then
+                echo "Branch is 'main'"
+                echo "##vso[task.setvariable variable=DeployFlag;isOutput=true]false"
+                echo "##vso[task.setvariable variable=CacheFlag;isOutput=true]false"
+                exit 0
+              fi
 
-              yq e ".$APP_NAME" "$CONFIG_FILE" > config.yml
+              if [ ! -e $(Build.SourcesDirectory)/app/Config ]; then
+                echo "DONE 2"
+                mkdir -p $(Build.SourcesDirectory)/app/Config
+                echo "DONE 3"
+              fi
 
-              if [ ! -s config.yml ]; then
-                echo "ERROR: Config not found for $APP_NAME"
+              echo "DONE 4"
+              yq e ".$applicationName | select(. !=null)" $(Build.SourcesDirectory)/eis-configurations/"$BRANCH"_config.yml > $(Build.SourcesDirectory)/app/Config/config_eis_configuration.yml
+              echo "DONE 5"
+
+              if [ -s $(Build.SourcesDirectory)/app/Config/config_eis_configuration.yml ]; then
+                echo "IN config_eis_configuration.yml"
+                config_path=$(Build.SourcesDirectory)/app/Config/config_eis_configuration.yml
+                cp "$config_path" $(Build.ArtifactStagingDirectory)
+              elif [ -s $(Build.SourcesDirectory)/app/Config/config.yml ]; then
+                echo "IN config.yml"
+                yq e ".$BRANCH" $(Build.SourcesDirectory)/app/Config/config.yml > $(Build.SourcesDirectory)/app/Config/temp.yml && mv $(Build.SourcesDirectory)/app/Config/temp.yml $(Build.SourcesDirectory)/app/Config/config.yml
+                config_path=$(Build.SourcesDirectory)/app/Config/config.yml
+                cat "$config_path"
+                cp "$config_path" $(Build.ArtifactStagingDirectory)
+              else
+                echo "ERROR: config.yml not found"
                 exit 1
               fi
 
-              cp config.yml $(Build.ArtifactStagingDirectory)
+              REQUIRED_FIELDS=(
+                IntegrationNode
+                IntegrationServer
+              )
+              for field in "${REQUIRED_FIELDS[@]}"; do
+                value=$(yq e ".$field // \"\"" "$config_path" | tr -d '[:space:]')
+                echo "Value: $value"
+                if [ -z "$value" ]; then
+                  echo " ERROR: $field is missing or empty "
+                  exit 1
+                fi
+              done
 
-              echo "##vso[task.setvariable variable=DeployFlag;isOutput=true]true"
+              DEPLOY=$(yq e ".Deploy" "$config_path" | tr -d '[:space:]')
+              CACHE_PRESENT=$(yq e ".Cache // [] | length > 0" "$config_path" | tr -d '[:space:]')
+              echo "CACHE: $CACHE_PRESENT DEPLOY: $DEPLOY"
+
+              if [ "$DEPLOY" = "false" ] || [ "$DEPLOY" = "False" ] || [ "$DEPLOY" = false ]; then
+                DEPLOY="false"
+              else
+                DEPLOY="true"
+              fi
+
+              if [ "$CACHE_PRESENT" = "true" ] || [ "$CACHE_PRESENT" = "True" ] || [ "$CACHE_PRESENT" = true ]; then
+                CACHE_PRESENT="true"
+              else
+                CACHE_PRESENT="false"
+              fi
+
+              if [ "$DEPLOY" != "true" ] && [ "$DEPLOY" != "false" ]; then
+                echo "Invalid Deploy flag in config.yml"
+                exit 1
+              fi
+
+              echo "##vso[task.setvariable variable=DeployFlag;isOutput=true]$DEPLOY"
+              echo "##vso[task.setvariable variable=CacheFlag;isOutput=true]$CACHE_PRESENT"
+
+
+        - task: PublishBuildArtifacts@1
+          condition: eq(variables['val_task.DeployFlag'], 'false')
+          inputs:
+            PathtoPublish: $(Build.ArtifactStagingDirectory)
+            ArtifactName: drop
 
 
 # ================= BUILD STAGE =================
 - stage: Build
+  displayName: Build Stage
   dependsOn: Validation_Stage
   pool:
     name: TFS-RH-1
 
+  condition: succeeded('Validation_Stage')
+
   jobs:
     - job: Build_Job
+      displayName: Agent Build job
+      workspace:
+        clean: all
       steps:
 
         - checkout: self
           path: s/app
 
+        - checkout: git://devops_testing/eis-configuration@refs/heads/config
+          path: s/eis-configurations
+
         - task: CmdLine@2
+          displayName: Building Bar file
           env:
-            APP_NAME: $(APP_NAME)
+            BRANCH: $(Build.SourceBranchName)
           inputs:
             script: |
               set -e
               . /opt/IBM/ace/server/bin/mqsiprofile
 
-              ibmint package \
-                --input-path $(Build.SourcesDirectory)/app \
-                --output-bar-file $(Build.BinariesDirectory)/$APP_NAME.bar \
-                --java-version 8
+              if [ -z "${{ parameters.applicationName }}" ]; then
+                applicationName=$(ls -1 $(Build.SourcesDirectory)/app | grep -vE "Config|README.md|azure-pipelines.yml" | tail -n 1)
+              else
+                applicationName="${{ parameters.applicationName }}"
+              fi
 
+              # For main branch, skip config resolution and build with source only
+              if [ "$BRANCH" = "main" ]; then
+                echo "Branch is 'main' — building without config"
+                ibmint package --input-path $(Build.SourcesDirectory)/app \
+                               --output-bar-file $(Build.BinariesDirectory)/$applicationName.bar \
+                               --java-version 8
+                mqsireadbar -b $(Build.BinariesDirectory)/$applicationName.bar -r | grep "=" | sed -e 's/^[[:space:]]*//' > $(Build.BinariesDirectory)/override.properties
+                exit 0
+              fi
+
+              if [ ! -e $(Build.SourcesDirectory)/app/Config ]; then
+                mkdir -p $(Build.SourcesDirectory)/app/Config
+              fi
+
+              yq e ".$applicationName" $(Build.SourcesDirectory)/eis-configurations/"$BRANCH"_config.yml > $(Build.SourcesDirectory)/app/Config/config_eis_configuration.yml
+
+              if [ -s $(Build.SourcesDirectory)/app/Config/config_eis_configuration.yml ]; then
+                cat "$(Build.SourcesDirectory)/app/Config/config_eis_configuration.yml" > $(Build.SourcesDirectory)/app/Config/config.yml
+                rm $(Build.SourcesDirectory)/app/Config/config_eis_configuration.yml
+              fi
+
+              config_path=$(Build.SourcesDirectory)/app/Config/config.yml
+              yq -i ".ApplicationName = \"$applicationName\"" "$config_path"
+
+              if [ "$BRANCH" != "DEV" ]; then
+                yq ".$applicationName| to_entries[] | .key + \" = \" + .value" $(Build.SourcesDirectory)/eis-configurations/"$BRANCH"_override.yml > $(Build.SourcesDirectory)/app/Config/override.properties
+              fi
+
+              if [ -f $(Build.SourcesDirectory)/app/Config/override.properties ]; then
+                override_path=$(Build.SourcesDirectory)/app/Config/override.properties
+              fi
+
+              if [ -s "$override_path" ]; then
+                ibmint package --input-path $(Build.SourcesDirectory)/app \
+                               --output-bar-file $(Build.BinariesDirectory)/$applicationName.bar \
+                               --java-version 8 \
+                               --overrides-file "$override_path"
+              else
+                ibmint package --input-path $(Build.SourcesDirectory)/app \
+                               --output-bar-file $(Build.BinariesDirectory)/$applicationName.bar \
+                               --java-version 8
+              fi
+
+              mqsireadbar -b $(Build.BinariesDirectory)/$applicationName.bar -r | grep "=" | sed -e 's/^[[:space:]]*//' > $(Build.SourcesDirectory)/app/Config/override.properties
+              cp $(Build.SourcesDirectory)/app/Config/* $(Build.BinariesDirectory)
+              cat "$config_path"
+
+
+        - task: CopyFiles@2
+          inputs:
+            SourceFolder: $(Build.BinariesDirectory)
+            TargetFolder: $(Build.ArtifactStagingDirectory)
+            OverWrite: true
+
+        - task: PublishBuildArtifacts@1
+          inputs:
+            PathtoPublish: $(Build.ArtifactStagingDirectory)
+            ArtifactName: drop
 
 
 # ================= RELEASE STAGE =================
-
 - stage: Release
+  displayName: Deploy Stage
+  pool:
+    name: TFS-RH-1
   dependsOn:
     - Validation_Stage
     - Build
-
-  condition: succeeded()
-
+  condition: |
+    and(
+      succeeded('Build'),
+      eq(
+        dependencies.Validation_Stage.outputs['Validation_Job.val_task.DeployFlag'],
+        'true'
+      ),
+      ne(variables['Build.SourceBranchName'], 'main')
+    )
   jobs:
-    - job: Deploy_All_EGs
-      steps:
+    - deployment: DeployApp
+      displayName: Deployment Job
+      environment: $(Build.SourceBranchName)
+      workspace:
+        clean: all
+      strategy:
+        runOnce:
+          deploy:
+            steps:
 
-        - download: current
-          artifact: drop
+              - download: current
+                artifact: drop
 
-        - task: CmdLine@2
-          env:
-            BRANCH: $(Build.SourceBranchName)
-            APP_NAME: $(APP_NAME)
-          inputs:
-            workingDirectory: $(Pipeline.Workspace)/drop
-            script: |
-              set -e
-              . /opt/IBM/ace/server/bin/mqsiprofile
+              - task: CmdLine@2
+                displayName: Deploying Bar File
+                env:
+                  BRANCH: $(Build.SourceBranchName)
+                inputs:
+                  workingDirectory: $(Pipeline.Workspace)/drop
+                  script: |
+                    set -e
+                    . /opt/IBM/ace/server/bin/mqsiprofile
 
-              CONFIG_FILE=$(Pipeline.Workspace)/drop/config.yml
+                    IntegrationNode=$(yq e ".IntegrationNode" config.yml)
+                    ApplicationName=$(yq e ".ApplicationName" config.yml)
+                    IntegrationServer=$(yq e ".IntegrationServer" config.yml)
 
-              IntegrationNode=$(yq e ".IntegrationNode" $CONFIG_FILE)
-              IntegrationServer=$(yq e ".IntegrationServer" $CONFIG_FILE)
-
-              echo "Node: $IntegrationNode"
-              echo "Server: $IntegrationServer"
-
-              echo "Deploying to ALL broker files..."
-
-              for broker_file in /home/devops/broker/$BRANCH/${IntegrationNode}_*.broker
-              do
-                echo "--------------------------------------"
-                echo "Processing $broker_file"
-
-                host=$(grep host $broker_file | cut -d'"' -f4)
-                eg=$(grep executionGroup $broker_file | cut -d'"' -f4)
-
-                echo "HOST: $host | EG: $eg"
-
-                ibmint deploy \
-                  --input-bar-file "$APP_NAME.bar" \
-                  --integration-node-file "$broker_file" \
-                  --output-server "$IntegrationServer"
-
-              done
-
+                    for broker_file in /home/devops/broker/$BRANCH/$IntegrationNode*; do
+                      fname=$(basename "$broker_file")
+                      if [[ $fname =~ ^${IntegrationNode}_([0-9]+)\.broker$ ]]; then
+                        cat "$broker_file" | grep host | awk -F"\"" '{print "HOST: " $4 " , " "IntegrationNode: " $6}'
+                        ibmint deploy \
+                          --input-bar-file "$ApplicationName.bar" \
+                          --integration-node-file "$broker_file" \
+                          --output-server "$IntegrationServer"
+                      fi
+                    done
